/**
 * Re-vendor from the repo. grammar.json stays the single source of truth; this only
 * changes how it is CARRIED.
 *
 * drift.ts does `import GRAMMAR from './grammar.json'`, which Wrangler's bundler resolves
 * and plain Node does not (ERR_IMPORT_ATTRIBUTE_MISSING). A published package cannot
 * assume a bundler, so the grammar is emitted as a TS module and the import rewritten.
 * Nothing is edited by hand — run this after any grammar or drift.ts change.
 */
import { readFileSync, writeFileSync, copyFileSync } from 'node:fs'

// Point this at your checkout of the worker. Absolute paths do not belong in a
// public repo, and the vendor step is only run by a maintainer.
const REPO = process.env.LASERBRAIN_WORKER_SRC
  || new URL('../phronesis-world/workers/laserbrain-mcp-remote', import.meta.url).pathname
const here = new URL('./src/', import.meta.url)

copyFileSync(`${REPO}/src/grammar.json`, new URL('grammar.json', here))
copyFileSync(`${REPO}/drift-vectors.json`,
             new URL('./test/drift-vectors.json', import.meta.url))

const grammar = readFileSync(`${REPO}/src/grammar.json`, 'utf8')
writeFileSync(new URL('grammar.ts', here),
  '// GENERATED by vendor.mjs from grammar.json — do not edit.\n' +
  '// The same grammar the Python package and the hosted API read.\n' +
  `export default ${grammar.trim()} as const\n`)

let drift = readFileSync(`${REPO}/src/drift.ts`, 'utf8')
const before = drift
drift = drift.replace(/from '\.\/grammar\.json'/, "from './grammar.js'")
if (drift === before) throw new Error('grammar.json import not found in drift.ts — check the vendor step')
writeFileSync(new URL('drift.ts', here), drift)

console.log('  vendored: drift.ts (import rewritten), grammar.ts, grammar.json, drift-vectors.json')
